### PR TITLE
Blade Feature Testing + Fix Rest API App

### PR DESCRIPTION
**Pull request by robzlabz**
This pull request add a Feature Testing to test functionality of Jepret Application

Updates: 
1. Add `.env.testing`
2. Add `make test` so we can test on docker
3. Add new docker file for testing on `testing.Dockerfile`
4. Add docker compose for Integration Testing
5. Add Feature Testing `HomeTest.php` with happy path and unhappy path

### CODE REVIEW

**Comment by fatkulnurk** [comment]
I tried running ```make test``` and it always failed. 

```
integration-testing-1  |    FAIL  Tests\Feature\HomeTest
integration-testing-1  |   ✓ access login page                                                    0.07s  
integration-testing-1  |   ⨯ successes login                                                      0.01s  
integration-testing-1  |   ⨯ field login                                                          0.01s  
integration-testing-1  |   ⨯ success upload image                                                 0.02s  
integration-testing-1  |   ⨯ failed caption                                                       0.01s  
integration-testing-1  |   ⨯ fail upload file big                                                 0.01s  
integration-testing-1  |   ✓ success access main                                                  0.01s  
integration-testing-1  |   ✓ unauthorized access                                                  0.01s  
integration-testing-1  |   ────────────────────────────────────────────────────────────────────────────  
integration-testing-1  |    FAILED  Tests\Feature\HomeTest > successes login                             
integration-testing-1  |   Expected response status code [302] but received 419.
integration-testing-1  | Failed asserting that 419 is identical to 302.
integration-testing-1  | 
integration-testing-1  |   at tests/Feature/HomeTest.php:25
integration-testing-1  |      21▕             'email' => 'alice@mail.com',
integration-testing-1  |      22▕             'password' => '123456',
integration-testing-1  |      23▕         ]);
integration-testing-1  |      24▕ 
integration-testing-1  |   ➜  25▕         $response->assertStatus(302);
integration-testing-1  |      26▕     }
integration-testing-1  |      27▕ 
integration-testing-1  |      28▕     public function testFieldLogin()
integration-testing-1  |      29▕     {
integration-testing-1  | 
integration-testing-1  |   ────────────────────────────────────────────────────────────────────────────  
integration-testing-1  |    FAILED  Tests\Feature\HomeTest > field login                                 
integration-testing-1  |   Session is missing expected key [errors].
integration-testing-1  | Failed asserting that false is true.
integration-testing-1  | 
integration-testing-1  |   at tests/Feature/HomeTest.php:36
integration-testing-1  |      32▕             'email' => 'not_found@gmail.com',
integration-testing-1  |      33▕             'password' => '123456',
integration-testing-1  |      34▕         ]);
integration-testing-1  |      35▕ 
integration-testing-1  |   ➜  36▕         $response->assertSessionHasErrors(['email']);
integration-testing-1  |      37▕         $response->assertStatus(302);
integration-testing-1  |      38▕     }
integration-testing-1  |      39▕ 
integration-testing-1  |      40▕     public function testSuccessUploadImage()
integration-testing-1  | 
integration-testing-1  |   ────────────────────────────────────────────────────────────────────────────  
integration-testing-1  |    FAILED  Tests\Feature\HomeTest > success upload image       LogicException   
integration-testing-1  |   GD extension is not installed.
integration-testing-1  | 
integration-testing-1  |   at vendor/laravel/framework/src/Illuminate/Http/Testing/FileFactory.php:77
integration-testing-1  |      73▕      */
integration-testing-1  |      74▕     protected function generateImage($width, $height, $extension)
integration-testing-1  |      75▕     {
integration-testing-1  |      76▕         if (! function_exists('imagecreatetruecolor')) {
integration-testing-1  |   ➜  77▕             throw new LogicException('GD extension is not installed.');
integration-testing-1  |      78▕         }
integration-testing-1  |      79▕ 
integration-testing-1  |      80▕         return tap(tmpfile(), function ($temp) use ($width, $height, $extension) {
integration-testing-1  |      81▕             ob_start();
integration-testing-1  | 
integration-testing-1  |       +2 vendor frames 
integration-testing-1  |   3   tests/Feature/HomeTest.php:46
integration-testing-1  | 
integration-testing-1  |   ────────────────────────────────────────────────────────────────────────────  
integration-testing-1  |    FAILED  Tests\Feature\HomeTest > failed caption             LogicException   
integration-testing-1  |   GD extension is not installed.
integration-testing-1  | 
integration-testing-1  |   at vendor/laravel/framework/src/Illuminate/Http/Testing/FileFactory.php:77
integration-testing-1  |      73▕      */
integration-testing-1  |      74▕     protected function generateImage($width, $height, $extension)
integration-testing-1  |      75▕     {
integration-testing-1  |      76▕         if (! function_exists('imagecreatetruecolor')) {
integration-testing-1  |   ➜  77▕             throw new LogicException('GD extension is not installed.');
integration-testing-1  |      78▕         }
integration-testing-1  |      79▕ 
integration-testing-1  |      80▕         return tap(tmpfile(), function ($temp) use ($width, $height, $extension) {
integration-testing-1  |      81▕             ob_start();
integration-testing-1  | 
integration-testing-1  |       +2 vendor frames 
integration-testing-1  |   3   tests/Feature/HomeTest.php:60
integration-testing-1  | 
integration-testing-1  |   ────────────────────────────────────────────────────────────────────────────  
integration-testing-1  |    FAILED  Tests\Feature\HomeTest > fail upload file big                        
integration-testing-1  |   Expected response status code [302] but received 419.
integration-testing-1  | Failed asserting that 419 is identical to 302.
integration-testing-1  | 
integration-testing-1  |   at tests/Feature/HomeTest.php:77
integration-testing-1  |      73▕             'image' => UploadedFile::fake()->create('image.jpg', 5000, 'image/jpeg'),
integration-testing-1  |      74▕             'caption' => 'Hello World!',
integration-testing-1  |      75▕         ]);
integration-testing-1  |      76▕ 
integration-testing-1  |   ➜  77▕         $response->assertStatus(302)
integration-testing-1  |      78▕             ->assertSessionHasErrors(['image']);
integration-testing-1  |      79▕     }
integration-testing-1  |      80▕ 
integration-testing-1  |      81▕     public function testSuccessAccessMain()
integration-testing-1  | 
integration-testing-1  | 
integration-testing-1  |   Tests:    5 failed, 3 passed (8 assertions)
integration-testing-1  |   Duration: 0.18s
integration-testing-1  | 
integration-testing-1 exited with code 2
Aborting on container exit...
[+] Stopping 3/3
 ✔ Container integration-testing-mysql-1                Stopped                                                                                                                                        1.9s 
 ✔ Container integration-testing-integration-testing-1  Stopped                                                                                                                                        0.0s 
 ✔ Container integration-testing-localstack-1           Stopped                                                                                                                                        0.8s 
make: *** [Makefile:9: test] Error 2

```

**Comment by riandyrn** [comment]
Nice finding, @fatkulnurk. 🎉

I think there are several issues when the test run in your local such as:

- missing GD extension
- CSRF token issue (419 status code usually related to CSRF token)
- the test cannot connected to the database (?)

I think the right way to solve this is by creating CI pipeline using Github Action that will execute "make test" command.

By doing this we can validate whether the issue is only on your local or it is universal. Because yesterday when we create this PR, I remember we can run all the test successfully.

Can you create PR for this, @fatkulnurk?

**Comment by robzlabz** [comment]
I've found the solution of this case, and i was implement on my local machine. Here's the result

```
integration-testing-1  | 
integration-testing-1  |    PASS  Tests\Feature\HomeTest
integration-testing-1  |   ✓ access login page                                                    0.37s  
integration-testing-1  |   ✓ successes login                                                      0.53s  
integration-testing-1  |   ✓ field login                                                          0.25s  
integration-testing-1  |   ✓ success upload image                                                 0.69s  
integration-testing-1  |   ✓ failed caption                                                       0.03s  
integration-testing-1  |   ✓ fail upload file big                                                 0.03s  
integration-testing-1  |   ✓ success access main                                                  0.04s  
integration-testing-1  |   ✓ unauthorized access                                                  0.02s  
integration-testing-1  | 
integration-testing-1  |   Tests:    8 passed (18 assertions)
integration-testing-1  |   Duration: 2.07s
```

What i've done:
1. Fix Env
2. Remoev '_token' => csrf_token(), because it does not necessary on testing
3. Add gd

Screenshot 2024-05-15 at 08 36 01

I keep this update on my local, this info maybe helpfull for @fatkulnurk

**Comment by robzlabz** [comment]
I will only push an update if allowed by @riandyrn 🤣

**Comment by fatkulnurk** [comment]
> Can you create PR for this, @fatkulnurk?

Yes, I will make a PR as soon as possible

**Review by riandyrn — APPROVED** [review]
LGTM. Great work, everyone!

**Pull request merged**
